image: proboci/ubuntu-14.04-lamp
assets:
  - README.md
  - README.md: readme

steps:
  - name: "quick task"
    plugin: 'Shell'
    command: "echo done > /dev/null"
  - name: "task 1"
    plugin: 'Shell'
    command: "sleep 1 && ps auxww; date"
  - name: "task 2"
    plugin: 'Shell'
    command: "sleep 2 &&  netstat -ant"
  - name: "show code"
    plugin: 'Shell'
    command: "ls -lh /code"
  - name: "task assets"
    plugin: 'Shell'
    command: "ls -lh /assets"
