image: lepew/ubuntu-14.04-lamp
steps:
  - name: "quick task"
    plugin: 'Shell'
    command: "echo done"
  # - name: "task 1"
  #   plugin: 'Shell'
  #   command: "sleep 3 && ps auxww; date"
  # - name: "task 2"
  #   plugin: 'Shell'
  #   command: "sleep 10 &&  netstat -ant"
