image: lepew/ubuntu-14.04-lamp
steps:
  - name: "quick task"
    plugin: 'Shell'
    command: "echo done > /dev/null"
  - name: "task 1"
    plugin: 'Shell'
    command: "sleep 1 && ps auxww; date"
  - name: "task 2"
    plugin: 'Shell'
    command: "sleep 2 &&  netstat -ant"
